name: money_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  calendar_appbar: ^0.0.6
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.1
  firebase_analytics: ^11.2.0
  firebase_core: ^3.1.1
  firebase_core_web: ^2.17.3
  animated_text_kit: ^4.2.1
  marquee: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

