// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5D50z6WK99ZAXfu87gImGyqni1F9c6NE',
    appId: '1:1021280905915:web:32ac5fb79dca60a447179e',
    messagingSenderId: '1021280905915',
    projectId: 'moneytracker-47236',
    authDomain: 'moneytracker-47236.firebaseapp.com',
    storageBucket: 'moneytracker-47236.appspot.com',
    measurementId: 'G-GTH6TKY4H4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJLZsbjqCVsfo_fDiJh_ruT7JXo9Y51OA',
    appId: '1:1021280905915:ios:c4ec71f71d32cfb147179e',
    messagingSenderId: '1021280905915',
    projectId: 'moneytracker-47236',
    storageBucket: 'moneytracker-47236.appspot.com',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5D50z6WK99ZAXfu87gImGyqni1F9c6NE',
    appId: '1:1021280905915:web:4214b0ed3d51ddbd47179e',
    messagingSenderId: '1021280905915',
    projectId: 'moneytracker-47236',
    authDomain: 'moneytracker-47236.firebaseapp.com',
    storageBucket: 'moneytracker-47236.appspot.com',
    measurementId: 'G-W7PQYYZCR9',
  );

}